version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates  # Add this line
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
